server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=utf8&useSSL=true
    username: root
    password: github
    driver-class-name: com.mysql.jdbc.Driver